### ISSUE TITLE
List of states needing their own landing page

### ISSUE THREAD

**Issue by schaar** [VoterAid2020/rollcall.voteOLD#4]

**Comment by schaar** [comment]
@arungm29 here's the list i'm thinking of:

- Texas
- Iowa
- Georgia
- Ohio
- North Carolina
- Florida
- Arizona
- Pennsylvania
- Wisconsin

@sheesh-who any others we should add here?

**Comment by sheesh-who** [comment]
Looks good— possibly Michigan?
